import{i,S as d}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function f(n){const r="https://pixabay.com",o="/api/",s=new URLSearchParams({key:"41636185-b642aedee9ddf38a3f46d8b56",q:n,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${r}${o}?${s}`;return fetch(e).then(t=>t.json()).catch(t=>{throw new Error(`HTTP error! status: ${res.status}`)})}function m(n){return n.reduce((r,{largeImageURL:o,webformatURL:s,tags:e,likes:t,views:a,comments:u,downloads:p})=>r+`<li class="gallery-item">
        <a href=${o}> 
          <img class="gallery-img" src=${s} alt="${e}"/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t}</span></p>
          <p>Views: <span class="text-value">${a}</span></p>
          <p>Comments: <span class="text-value">${u}</span></p>
          <p>Downloads: <span class="text-value">${p}</span></p>
        </div>
      </li>`,"")}const y=document.querySelector(".form"),l=document.querySelector(".gallery"),g=document.getElementById("search-input"),c=document.querySelector(".loader");y.addEventListener("submit",async n=>{n.preventDefault();const r=g.value.trim();if(r===""){i.error({message:"Please enter text",position:"topCenter"});return}c.style.display="block",l.innerHTML="";try{const o=await f(r);if(o.hits.length>0){const s=m(o.hits);l.innerHTML=s,new d(".gallery a",{nav:!0,captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}).refresh()}else i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}catch(o){console.error("Error:",o),i.error({message:"An error occurred. Try again later.",position:"topCenter"})}finally{c.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
